parameter_defaults:
  NeutronExternalNetworkBridge: "''"
  NeutronBridgeMappings: "''"
  NeutronEnableIsolatedMetadata: 'True'
  NeutronNetworkType: 'vxlan,gre,vlan,flat'
  NeutronTunnelTypes: 'vxlan,gre'
