resource_registry:
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/ceph-storage.yaml

  OS::TripleO::CNCFBaremetal::Net::SoftwareConfig: /home/stack/templates/nic-configs/cncfbare.yaml
  OS::TripleO::CNCFNetworker::Net::SoftwareConfig: /home/stack/templates/nic-configs/networker.yaml

  OS::TripleO::CNCFNetworker::Ports::ExternalPort: /usr/share/openstack-tripleo-heat-templates/network/ports/external.yaml
  OS::TripleO::CNCFNetworker::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/internal_api.yaml
  OS::TripleO::CNCFNetworker::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::CNCFNetworker::Ports::StorageMgmtPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::CNCFNetworker::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/tenant.yaml

  OS::TripleO::CNCFBaremetal::Ports::ExternalPort: /usr/share/openstack-tripleo-heat-templates/network/ports/external.yaml
  OS::TripleO::CNCFBaremetal::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/internal_api.yaml
  OS::TripleO::CNCFBaremetal::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::CNCFBaremetal::Ports::StorageMgmtPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::CNCFBaremetal::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/tenant.yaml

parameter_defaults:

  ExternalNetName: external2
  InternalApiNetName: internal_api2
  StorageMgmtNetName: storagemgt2
  StorageNetName: storage2
  TenantNetName: tenant2

  ExternalSubnetName: external_subnet2
  InternalSubnetName: internal_api_subnet2
  StorageMgmtSubnetName: storagemgmt_subnet2
  StorageSubnetName: storage_subnet2
  TenantSubnetName: tenant_subnet2

  InternalApiNetValueSpecs:
      'provider:physical_network': 'internal_api2'
      'provider:network_type': 'flat'
  ExternalNetValueSpecs:
      'provider:physical_network': 'external2'
      'provider:network_type': 'flat'
  StorageNetValueSpecs:
      'provider:physical_network': 'storage2'
      'provider:network_type': 'flat'
  StorageMgmtNetValueSpecs:
      'provider:physical_network': 'storagemgt2'
      'provider:network_type': 'flat'
  TenantNetValueSpecs:
      'provider:physical_network': 'tenant2'
      'provider:network_type': 'flat'

  NeutronDhcpAgentsPerNetwork: 2
  InternalApiNetCidr: 172.16.0.0/16
  TenantNetCidr: 172.17.0.0/16
  StorageNetCidr: 172.18.0.0/16
  StorageMgmtNetCidr: 172.19.0.0/16
  ManagementNetCidr: 172.20.0.0/16
  ControlPlaneSubnetCidr: 16
  ExternalNetCidr: 10.2.4.0/21
  InternalApiAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.5.200'}]
  TenantAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.5.200'}]
  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.5.200'}]
  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.5.200'}]
  ManagementAllocationPools: [{'start': '172.20.0.10', 'end': '172.20.5.200'}]
  ExternalAllocationPools: [{'start': '10.2.4.109', 'end': '10.2.5.55'}]
  ExternalInterfaceDefaultRoute: 10.2.0.1
  ControlPlaneDefaultRoute: 192.0.2.1
  EC2MetadataIp: 192.0.2.1
  DnsServers: ["8.8.8.8","8.8.4.4"]
  InternalApiNetworkVlanID: 282
  StorageNetworkVlanID: 283
  StorageMgmtNetworkVlanID: 284
  TenantNetworkVlanID: 285
  ManagementNetworkVlanID: 286
  ExternalNetworkVlanID: 7
  # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
  NeutronExternalNetworkBridge: "''"
  # Customize bonding options if required
  BondInterfaceOvsOptions:
    "bond_mode=balance-tcp"
