---

resource_registry:
  OS::TripleO::NodeUserData: /home/stack/templates/first-boot-template.yaml
  OS::TripleO::Services::CephMon: /usr/share/openstack-tripleo-heat-templates/puppet/services/ceph-mon.yaml
  OS::TripleO::Services::CephOSD: /usr/share/openstack-tripleo-heat-templates/puppet/services/ceph-osd.yaml
  OS::TripleO::Services::CephClient: /usr/share/openstack-tripleo-heat-templates/puppet/services/ceph-client.yaml

parameter_defaults:
  CinderEnableIscsiBackend: false
  CinderEnableRbdBackend: true
  CinderBackupBackend: ceph
  NovaEnableRbdBackend: true
  GlanceBackend: rbd
  GnocchiBackend: rbd
  CephPools:
    vms:
      pg_num: 3000
      pgp_num: 3000
  ExtraConfig:
    #ceph::profile::params::fsid: eb2bb192-b1c9-11e6-9205-525400330667
    ceph::profile::params::osd_pool_default_pg_num: 256
    ceph::profile::params::osd_pool_default_pgp_num: 256
    ceph::profile::params::osd_pool_default_size: 3
    ceph::profile::params::osd_pool_default_min_size: 2
    ceph::profile::params::osd_recovery_max_active: 1
    ceph::profile::params::osd_max_backfills: 1
    ceph::profile::params::osd_recovery_op_priority: 1
    ceph::profile::params::osd_journal_size: 10240
    ceph::profile::params::osds:
      '/dev/sdc':
        journal: '/dev/sdb'
      '/dev/sdd':
        journal: '/dev/sdb'
      '/dev/sde':
        journal: '/dev/sdb'
      '/dev/sdf':
        journal: '/dev/sdb'
      '/dev/sdg':
        journal: '/dev/sdb'
      '/dev/sdh':
        journal: '/dev/sdb'
      '/dev/sdi':
        journal: '/dev/sdb'
      '/dev/sdj':
        journal: '/dev/sdb'
      '/dev/sdk':
        journal: '/dev/sdb'
      '/dev/sdl':
        journal: '/dev/sdb'
