heat_template_version: 2014-10-16

description: >
  First boot script if necessary

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: first_boot}

  first_boot:
    type: OS::Heat::SoftwareConfig
    properties:
      config: {get_file: first-boot-script.sh}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}